[package]
name = "khe"
version = "0.0.1"
edition = "2021"

[dependencies]
moo = { path = "../moo" }
winit = { version = "0.29", features = ["rwh_05"] }
wgpu = "0.19"
bytemuck = { version = "1", features = ["derive"] }
glam = "0.25"
pollster = "0.3"
egui = "0.26"
egui-wgpu = "0.26"
egui-winit = "0.26"
